spring.application.name=gestionacademica
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/academica_db
spring.datasource.username=colegio
spring.datasource.password=colegio
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect