spring.application.name=asistencia
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/asistencia_db
spring.datasource.username=colegio
spring.datasource.password=colegio
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

resilience4j.circuitbreaker.instances.comunicacionesService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.comunicacionesService.sliding-window-size=5
resilience4j.circuitbreaker.instances.comunicacionesService.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.comunicacionesService.permitted-number-of-calls-in-half-open-state=3