spring.application.name=eurekaServer
server.port=8761

eureka.client.register-with-eureka=false
eureka.server.renewal-percent-threshold=0.85
eureka.instance.lease-expiration-duration-in-seconds=10
eureka.server.enable-self-preservation=true
