spring.application.name=apigateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=gestionacademica
spring.cloud.gateway.routes[0].uri=lb://gestionacademica
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/academica/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/academica/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=asistencia
spring.cloud.gateway.routes[1].uri=lb://asistencia
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/asistencia/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/asistencia/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[2].id=comunicaciones
spring.cloud.gateway.routes[2].uri=lb://comunicaciones
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/comunicaciones/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/comunicaciones/(?<segment>.*), /${segment}
